  // Operational Expenditure Observations (Non-Obligation)
  OBSERVED_TOKEN_REALIZATION: 4000,
  OBSERVED_PSP_EXPENSE: 6000,
  OBSERVED_CHASE_EXPENSE: 6100,
  OBSERVED_AMZON_EXPENSE: 6200,
  OBSERVED_ANCHOR_FULFILLMENT_EXPENSE: 6300,
  OBSERVED_ANCHOR_CARD_EXPENSE: 6001,

  // Authorization Memos (Non-Obligation Shadow Accounts)
  ANCHOR_GROCERY_AUTHORIZATION_MEMO: 3500,
  ANCHOR_UTILITY_AUTHORIZATION_MEMO: 3501,
  ANCHOR_FUEL_AUTHORIZATION_MEMO: 3504,
  ANCHOR_MOBILE_AUTHORIZATION_MEMO: 3505,
  ANCHOR_HOUSING_AUTHORIZATION_MEMO: 3506,
  ANCHOR_MEDICAL_AUTHORIZATION_MEMO: 3507,

  // Equity / Income Observations
  OBSERVED_TOKEN_REALIZATION: 4000,

  // E2E Finality System (New Component)
  E2E_HONORING_LEDGER: 5000,
  E2E_DISPATCHER_QUEUE: 5001,
  E2E_HONORING_TRACKING: 5002,
  E2E_CREDIT_MANAGEMENT: 5003,
  E2E_ALERTS: 5004,
